name: 04 - Using Actions
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - run: bun install
        working-directory: ./04-using-actions

      - name: Start bun dev in background
        run: |
          bun dev &             # Run bun dev in background
          echo $! > bun.pid     # Save its PID
        working-directory: ./04-using-actions
      - name: Run tests
        run: |
          sleep 3
          bun test
        continue-on-error: false  # fail workflow if tests fail
        working-directory: ./04-using-actions

      - name: Kill bun dev background process
        if: ${{ success() }}
        run: |
          kill $(cat bun.pid)
        working-directory: ./04-using-actions
