name: 04 - Using Actions
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - run: bun install

      - name: Start bun dev in background
        run: |
          bun dev &             # Run bun dev in background
          echo $! > bun.pid     # Save its PID
      
      - name: Wait for bun dev to be ready
        run: |
          # Example: simple sleep for 5 seconds
          sleep 3
          # Or use curl/wait-on to poll and confirm readiness

      - name: Run tests
        run: bun test
        continue-on-error: false  # fail workflow if tests fail

      - name: Kill bun dev background process
        if: ${{ success() }}
        run: |
          kill $(cat bun.pid)
