name: 09 - Using Functions
on:
  - pull_request
  - workflow_dispatch
jobs:
  echo-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Pr Title
        run: echo "The PR title is ${{ github.event.pull_request.title }}"

      - name: Print Pr Labels
        run: |
          cat << EOF
          ${{ toJSON(github.event.pull_request.labels) }}
          EOF

      - name: Bug Step
        run: echo "I am a bug fix."
        if: ${{ failure() && !cancelled() && contains(github.event.pull_request.title,'fix') }}
      - name: Sleep for 5 seconds
        run: sleep 5

      - name: Failing step
        run: exit 1

      - name: I will be skipped
        run: echo "This step is skipped because the previous step failed"
        if: ${{ success() }}
      - name: I will execute
        run: echo "This step runs because the previous step failed"
        if: ${{ failure() }}
      - name: I will execute
        run: echo "I will always print except when the workflow is cancelled"
        if: ${{!cancelled() }}
      - name: "I will execute when the workflow is cancelled"
        run: echo "This step runs only when the workflow is cancelled"
        if: ${{ cancelled() }}