name: 11 - Working with Inputs
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Skip deployment and only print build output"
        type: boolean
        default: false
      target:
        description: "Which environment the workflow will target"
        required: true
        type: environment
      tag:
        description: "Release from which to build and deploy"
        type: choice
        options:
          - v1.0
          - v2.0
          - v3.0
        default: v3.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building the project for tag ${{ inputs.tag }}..."
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !inputs.dry_run }}
    environment: ${{ inputs.target }}
    steps:
      - name: Deploy
        run: echo "Deploying the project to environment ${{ inputs.target }}..."
